### ISSUE TITLE
Web browser stream 

### ISSUE THREAD

**Issue by rafyzg** [hub-gain/py-tisgrabber#1]
Hey Bastian,

Thank you very much for the package development, it is very useful.
I was wondering if you know a way I could video stream from the camera to the browser? 
I saw an official example from TIS but unfortunately it only supports linux. 
https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/master/python/webserver/tcam_webserver.py

Is it possible to implement it in windows?
Thanks.

**Comment by bleykauf** [comment]
Glad to hear that you find the package useful :)

Unfortunately, I do not know how to stream to the browser and I most probably will not have the time to look into it since I primarily wrote this package for an Qt based app.

If you do find out how it works, I am happy for a pull request. I did write an issue on https://github.com/TheImagingSource and got a reply pretty quickly. Maybe try your luck there.
